### PR TITLE
Resolved "Invalid Email" Error from faculty login

### PR DESCRIPTION
**Pull request by pranavbavdhankar**
## PR Description
This is the resolve the issue #69.
User is now able to login as faculty as well.

### CODE REVIEW

**Comment by Pranav0606** [comment]
Hey @aswinikalyan30 , Added the remember me feature as well!
Issue #70

**Review by aswinikalyan30 — APPROVED** [review]

**Comment by aswinikalyan30** [comment]
Looks like there is a conflict, can you resolve them?

**Comment by pranavbavdhankar** [comment]
Hey, @aswinikalyan30 have a look on the changes!

**Comment by pranavbavdhankar** [comment]
@aswinikalyan30 have a look on these changes!

**Review by sk-upadhyay — COMMENTED** [review]
you should merge the index and admin class as it solved the problem and the i have not getting login and signup as i have changed according to me

**Pull request closed without merging**
