### PR TITLE
Added UI Icons to the signup page

### LINKED ISSUE #48: Change the UI Icons on signup page
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

image

UI Elements plays an important role for user interaction. 
On signup page there are various input fields.
I have seen that most of them have the same icon which may be bit confusing for the user. 
I would like to change some icons on signup page to make it user friendly.
Assign this issue to me.

### Record

- [X] I'm a GSSOC'24 contributor
- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by Pranav0606**
## PR Description

_Add your description_

## Related Issues: Issue for which you are raising a PR for

- Closes #48 

### Issue

[Issue number or description]

### Checklist

- [x] I have gone through the [contributing guide](https://github.com/SaiyamTuteja/Faculty_Evaluation_System/blob/main/CONTRIBUTING.md)
- [x] I have updated my branch and synced it with project `main` branch before making this PR
- [ ] Is this a bug fix/enhancement/documentation changes
- [x] Part of GSSOC
- [x] Tested for any breaking changes
- [x] Other relevant checks completed

## Undertaking

I declare that: 

1. The content I am submitting is original and has not been plagiarized.  
2. No portion of the work has been copied from any other source without proper attribution.  
3. The work has been checked for plagiarism, and I assure its authenticity.  

I understand that any violation of this undertaking may have legal consequences that I will bear and could result in the withdrawal of any recognition associated with the work. 

- [x] I Agree

### CODE REVIEW

**Comment by aswinikalyan30** [comment]
Hey, can you update with screenshots?

**Review by aswinikalyan30 — COMMENTED** [review]
I can't find anything that was changed except for spacing.

**Comment by aswinikalyan30** [comment]
Any updates on this @Pranav0606 ?

**Comment by Pranav0606** [comment]
Sorry!
Seems I have made a wrong pull request @aswinikalyan30 !
I'll correct it!

**Pull request closed without merging**
