### PR TITLE
#33 BUG: No changes made to account details but still get a "username already exists solved

### PR DESCRIPTION
**Pull request by sk-upadhyay**
## PR Description

updated login, signup, manage_user,admin_class

## Related Issues: Issue for which you are raising a PR for

- Closes #

### Issue

[#33  solved]

### Checklist

- [x] I have gone through the [contributing guide](https://github.com/SaiyamTuteja/Faculty_Evaluation_System/blob/main/CONTRIBUTING.md)
- [x] I have updated my branch and synced it with project `main` branch before making this PR
- [x] Is this a bug fix/enhancement/documentation changes
- [x] Part of GSSOC
- [x] Tested for any breaking changes
- [x] Other relevant checks completed

## Undertaking

I declare that: 

1. The content I am submitting is original and has not been plagiarized.  
2. No portion of the work has been copied from any other source without proper attribution.  
3. The work has been checked for plagiarism, and I assure its authenticity.  

I understand that any violation of this undertaking may have legal consequences that I will bear and could result in the withdrawal of any recognition associated with the work. 

- [x] I Agree

### CODE REVIEW

**Comment by aswinikalyan30** [comment]
Hey, I am seeing a lot of irrelevant files added to PR, can you have a look?

**Comment by sk-upadhyay** [comment]
yeah i don't know why is this is happening there is major changes in login, signup, manage_user,admin_class you can merge the specific file

**Comment by Pranav0606** [comment]
@aswinikalyan30 have you merged it?

**Comment by aswinikalyan30** [comment]
Could you discard the files? Not able to merge only those files

**Comment by sk-upadhyay** [comment]
@aswinikalyan30 hey can you help me with how to do that on discord i don't know what happened

**Comment by aswinikalyan30** [comment]
@sk-upadhyay , I suggest you can copy these changes to another set of files, delete the repo from local and re-clone it. And then add these changes

**Comment by sk-upadhyay** [comment]
Okay @aswinikalyan30 let me check

**Pull request closed without merging**
