### PR TITLE
Fix#32: Change TEXT to VARCHAR for avatar columns to allow default va…

### LINKED ISSUE #32: BUG: Not able to run evaluation_db queries - value of Avatar cannot be set to null
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What went down?

image

Modify the queries wherever "avatar" coloumn is present - change it to a **datatype** that can have the above default value

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSOC'24 contributor
- [ ] I want to work on this issue

### PR DESCRIPTION
**Pull request by Swapnilden**
…lues

## PR Description
- Modified `faculty_list` and `student_list` tables to use VARCHAR(255) for `avatar` column instead of TEXT.

- Ensured compatibility with MySQL/MariaDB constraints regarding default values for BLOB/TEXT columns.

Problem
Screenshot (32)_LI

Problem Solved
Screenshot (31)_LI

## Related Issues: Issue for which you are raising a PR for

- Closes #32 

### Issue

#32 

### Checklist

- [x] I have gone through the [contributing guide](https://github.com/SaiyamTuteja/Faculty_Evaluation_System/blob/main/CONTRIBUTING.md)
- [x] I have updated my branch and synced it with project `main` branch before making this PR
- [x] Is this a bug fix/enhancement/documentation changes
- [x] Part of GSSOC
- [ ] Tested for any breaking changes
- [ ] Other relevant checks completed

## Undertaking

I declare that: 

1. The content I am submitting is original and has not been plagiarized.  
2. No portion of the work has been copied from any other source without proper attribution.  
3. The work has been checked for plagiarism, and I assure its authenticity.  

I understand that any violation of this undertaking may have legal consequences that I will bear and could result in the withdrawal of any recognition associated with the work. 

- [x] I Agree

### CODE REVIEW

**Review by aswinikalyan30 — CHANGES_REQUESTED** [review]
Change the one for `users` table too. Otherwise looks good 💯

**Comment by Swapnilden** [comment]
Okay

**Review by Swapnilden — COMMENTED** [review]
I have done it

**Review by aswinikalyan30 — APPROVED** [review]
Great work! 🚀

**Pull request merged**
