### PR TITLE
logo added

### LINKED ISSUE #16: Feat: Give a unique name for the project and create a logo for the same
### Describe the feature

The current system is built for a specific college - make it as a generalised project with which any college can integrate

### Add ScreenShots

image

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSOC'24 contributor
- [ ] I want to work on this issue

### PR DESCRIPTION
**Pull request by aindree-2005**
## PR Description

_Add your description_

## Related Issues: Issue for which you are raising a PR for

- Closes #16 

### Issue

[Issue number or description]

### Checklist

- [x] I have gone through the [contributing guide](https://github.com/SaiyamTuteja/Faculty_Evaluation_System/blob/main/CONTRIBUTING.md)
- [x] I have updated my branch and synced it with project `main` branch before making this PR
- [x] Is this a bug fix/enhancement/documentation changes
- [x] Part of GSSOC
- [x] Tested for any breaking changes
- [x] Other relevant checks completed

## Undertaking

I declare that: 

1. The content I am submitting is original and has not been plagiarized.  
2. No portion of the work has been copied from any other source without proper attribution.  
3. The work has been checked for plagiarism, and I assure its authenticity.  

I understand that any violation of this undertaking may have legal consequences that I will bear and could result in the withdrawal of any recognition associated with the work. 

- [x] I Agree

### CODE REVIEW

**Comment by aindree-2005** [comment]
@aswinikalyan30 added logo to main file and replaced it in login,php.

**Review by aswinikalyan30 — CHANGES_REQUESTED** [review]
Please add it to signup.php too!
Otherwise, looks great! ✨

**Comment by aindree-2005** [comment]
> Please add it to signup.php too! Otherwise, looks great! ✨

@aswinikalyan30 added it to signup!

**Review by aswinikalyan30 — APPROVED** [review]
Thanks for your contributions 🚀

**Pull request merged**
