### PR TITLE
create contributors page

### PR DESCRIPTION
**Pull request by mahek0620**
Related Issues: Issue for which you are raising a PR for
Closes improving readme file  #59
Issue

ISSUE #59 

Checklist
[X]I have gone through the [contributing guide (https://github.com/SaiyamTuteja/Faculty_Evaluation_System/blob/main/CONTRIBUTING.md)
[X] I have updated my branch and synced it with project main branch before making this PR
[X] Is this a bug fix/enhancement/documentation changes
[X] Part of GSSOC
[X]Tested for any breaking changes

### CODE REVIEW

**Comment by mahek0620** [comment]
linked contributors page to index.php

**Comment by mahek0620** [comment]
@aswinikalyan30 by mistake the previous pull request was closed, so I created a new one

**Comment by mahek0620** [comment]
@aswinikalyan30 can you review and add labels to this

**Comment by aswinikalyan30** [comment]
Hey, looks like there are some conflicts, can you take a pull?

**Comment by mahek0620** [comment]
@aswinikalyan30 can you review it

**Review by aswinikalyan30 — APPROVED** [review]

**Pull request merged**
