### PR TITLE
Create CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by prajwaldp223**
created code of conduct to fix the issue #3

### CODE REVIEW

**Comment by prajwaldp223** [comment]
This fixes #15 issues @SaiyamTuteja

**Comment by aswinikalyan30** [comment]
> This fixes #15 issues @SaiyamTuteja

Hey @prajwaldp223 , I am sorry, but since #15 was not assigned to you, you can't directly raise the PR for it.
Please update this PR with only the code of conduct

**Review by aswinikalyan30 — CHANGES_REQUESTED** [review]
remove the code of conduct file from this PR and keep only the PR template one
Even in the PR template, like mentioned in issue #15 add the other checklist items too

**Comment by prajwaldp223** [comment]
@aswinikalyan30 removed the code of conduct file!!!

**Comment by prajwaldp223** [comment]
can u recheck for the updated pull request template !!

**Review by aswinikalyan30 — APPROVED** [review]
Looks good👍

**Pull request merged**
