### PR TITLE
LEARN.md

### PR DESCRIPTION
**Pull request by Passionatelytoooadorable**
Updated Learn.md

### CODE REVIEW

**Comment by aswinikalyan30** [comment]
Can you link the respective issue on the PR description?

**Review by aswinikalyan30 — APPROVED** [review]
Great work!

**Comment by Passionatelytoooadorable** [comment]
> Can you link the respective issue on the PR description?

Sure.
Link of res. issue : https://github.com/SaiyamTuteja/Faculty_Evaluation_System/issues/1

**Comment by Passionatelytoooadorable** [comment]
Link for the issue #1 is attached in description

**Pull request merged**
